global using Api.Helpers;
global using FluentValidation;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Routing;
global using Utilities.CQRS;
global using Utilities.Helpers;
global using Utilities.Results;
