#!/bin/bash
################################################################################
# React OpenAPI Client Generation Script for macOS/Linux
################################################################################
# This script generates TypeScript API client from OpenAPI specification
# Optimized for React with Fetch API and modern TypeScript patterns
#
# Usage: ./generate-react-client.sh [base-url] [backend-project-path]
# Examples:
#   ./generate-react-client.sh
#   ./generate-react-client.sh http://localhost:5000
#   ./generate-react-client.sh http://api.example.com ../../backend/.NET/template
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Defaults
BASE_URL="${1:-http://localhost:5000}"
BACKEND_PROJECT="${2:-../../backend/.NET/template}"
OUTPUT_DIR="../generated/react"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="openapi-generator-react.json"

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_ok() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Header
echo ""
echo "================================================================================"
echo " REACT OPENAPI CLIENT GENERATION"
echo "================================================================================"
echo ""

log_info "Base URL: $BASE_URL"
log_info "Backend Project: $BACKEND_PROJECT"
log_info "Output Directory: $OUTPUT_DIR"
log_info "Config: $CONFIG_FILE"
echo ""

# Check if NSwag is installed
log_info "Checking for NSwag..."
if ! command -v nswag &> /dev/null; then
    log_warning "NSwag CLI not found. Installing..."
    npm install -g @nswag/cli
    if [ $? -ne 0 ]; then
        log_error "Failed to install NSwag. Please run: npm install -g @nswag/cli"
        exit 1
    fi
fi
log_ok "NSwag is available"
echo ""

# Check if backend project exists
if [ ! -d "$SCRIPT_DIR/$BACKEND_PROJECT" ]; then
    log_warning "Backend project not found at: $SCRIPT_DIR/$BACKEND_PROJECT"
    log_info "Proceeding with existing OpenAPI spec or using provided URL..."
else
    log_ok "Backend project found"
fi

# Check if the API is running
log_info "Checking if API is running at $BASE_URL..."
if curl -s "$BASE_URL/health" > /dev/null 2>&1; then
    log_ok "API is running"
else
    log_warning "API might not be running at $BASE_URL"
    log_info "The generation will fail if the OpenAPI spec cannot be fetched"
fi

# Create output directory
mkdir -p "$OUTPUT_DIR/src/api"
log_ok "Output directory created: $OUTPUT_DIR"
echo ""

# Download and cache OpenAPI spec
log_info "Fetching OpenAPI specification from $BASE_URL/openapi/v1.json..."
if ! curl -s "$BASE_URL/openapi/v1.json" -o "/tmp/openapi-spec-react.json"; then
    log_error "Failed to download OpenAPI specification"
    log_info "Ensure the API is running at $BASE_URL and accessible"
    exit 1
fi
log_ok "OpenAPI specification fetched"

# Verify the spec file
if [ ! -f "/tmp/openapi-spec-react.json" ]; then
    log_error "OpenAPI spec file not created"
    exit 1
fi

# Generate TypeScript client using NSwag
echo ""
log_info "Generating TypeScript client using NSwag..."
log_info "Configuration: $CONFIG_FILE"

nswag run "$CONFIG_FILE" /variables:BaseUrl="$BASE_URL"

if [ $? -eq 0 ]; then
    log_ok "Client generation completed successfully"
else
    log_error "Client generation failed"
    exit 1
fi

# Verify generated files
echo ""
if [ -f "$OUTPUT_DIR/src/api/generated.ts" ]; then
    log_ok "Generated client file: $OUTPUT_DIR/src/api/generated.ts"
    log_info "File size: $(du -h "$OUTPUT_DIR/src/api/generated.ts" | cut -f1)"
else
    log_error "Generated client file not found"
    exit 1
fi

# Create index file for easier imports
log_info "Creating index file for exports..."
cat > "$OUTPUT_DIR/src/api/index.ts" << 'EOF'
/**
 * Auto-generated API Client from OpenAPI specification
 * Generated by: generate-react-client.sh
 * 
 * DO NOT EDIT: This file is generated automatically.
 * Any changes will be overwritten when regenerating.
 */

export * from './generated';
EOF
log_ok "Index file created"

# Format generated files
if command -v prettier &> /dev/null; then
    log_info "Formatting generated code with Prettier..."
    prettier --write "$OUTPUT_DIR/src/api/generated.ts" 2>/dev/null || log_warning "Prettier formatting failed (non-critical)"
    log_ok "Code formatted"
else
    log_warning "Prettier not installed. Skipping code formatting..."
fi

# Generate documentation
echo ""
log_info "Generating client documentation..."
cat > "$OUTPUT_DIR/README.md" << EOF
# Auto-Generated React API Client

Generated from OpenAPI specification at: $BASE_URL/openapi/v1.json

## Generated Files

- \`src/api/generated.ts\` - Main API client and types
- \`src/api/index.ts\` - Export barrel for easier imports

## Usage

### Import the Client

\`\`\`typescript
import { TodoApiClient } from '@/api/generated';

const apiClient = new TodoApiClient();
\`\`\`

### Make API Calls

\`\`\`typescript
const todos = await apiClient.getTodos(1, 10);
\`\`\`

## Regenerating the Client

To regenerate the client after API changes:

\`\`\`bash
cd clients/generation
./generate-react-client.sh
\`\`\`

## Important Notes

- ⚠️ **DO NOT EDIT** the generated files directly
- Generated files are overwritten on every regeneration
- All customizations should be done in wrapper/adapter classes
- Extend the generated client classes if you need custom behavior

## Generated at

$(date)
EOF
log_ok "Documentation created"

# Summary
echo ""
echo "================================================================================"
echo " GENERATION COMPLETE"
echo "================================================================================"
log_ok "React API client generated successfully!"
echo ""
log_info "Next steps:"
echo "  1. Install/update dependencies in React project"
echo "  2. Import from: import { TodoApiClient } from '@/api/generated'"
echo "  3. Create API client instance and use in your code"
echo ""
log_info "Generated files location: $OUTPUT_DIR"
echo ""
