@echo off
REM ============================================================================
REM React OpenAPI Client Generation Script for Windows (PowerShell)
REM ============================================================================
REM This script generates TypeScript API client from OpenAPI specification
REM Optimized for React with Fetch API and modern TypeScript patterns
REM
REM Usage: .\generate-react-client.bat [base-url] [backend-project-path]
REM Examples:
REM   .\generate-react-client.bat
REM   .\generate-react-client.bat http://localhost:5000
REM   .\generate-react-client.bat http://api.example.com ..\..\backend\.NET\template
REM ============================================================================

setlocal enabledelayedexpansion

echo.
echo ============================================================================
echo  REACT OPENAPI CLIENT GENERATION
echo ============================================================================
echo.

REM Default values
set "BASE_URL=http://localhost:5000"
set "BACKEND_PROJECT=..\..\backend\.NET\template"
set "OUTPUT_DIR=..\generated\react"
set "SCRIPT_DIR=%~dp0"
set "CONFIG_FILE=openapi-generator-react.json"

REM Parse command line arguments
if not "%1"=="" (
    set "BASE_URL=%1"
)
if not "%2"=="" (
    set "BACKEND_PROJECT=%2"
)

echo [INFO] Base URL: %BASE_URL%
echo [INFO] Backend Project: %BACKEND_PROJECT%
echo [INFO] Output Directory: %OUTPUT_DIR%
echo [INFO] Config: %CONFIG_FILE%
echo.

REM Check if NSwag is installed
echo [INFO] Checking for NSwag...
where nswag >nul 2>nul
if errorlevel 1 (
    echo [WARNING] NSwag CLI not found. Installing globally...
    call npm install -g @nswag/cli
    if errorlevel 1 (
        echo [ERROR] Failed to install NSwag. Please run: npm install -g @nswag/cli
        exit /b 1
    )
)
echo [OK] NSwag is available
echo.

REM Check if backend project exists
if exist "%SCRIPT_DIR%%BACKEND_PROJECT%" (
    echo [OK] Backend project found
) else (
    echo [WARNING] Backend project not found at: %SCRIPT_DIR%%BACKEND_PROJECT%
    echo [INFO] Proceeding with existing OpenAPI spec or using provided URL...
)

REM Check if the API is running
echo [INFO] Checking if API is running at %BASE_URL%...
powershell -NoProfile -Command "try { $null = Invoke-WebRequest -Uri '%BASE_URL%/health' -ErrorAction Stop; Write-Host '[OK] API is running' } catch { Write-Host '[WARNING] API might not be running at %BASE_URL%' }"

echo.

REM Create output directory
if not exist "%OUTPUT_DIR%\src\api" (
    mkdir "%OUTPUT_DIR%\src\api"
    if errorlevel 1 (
        echo [ERROR] Failed to create output directory
        exit /b 1
    )
)
echo [OK] Output directory created: %OUTPUT_DIR%
echo.

REM Download OpenAPI spec
echo [INFO] Fetching OpenAPI specification from %BASE_URL%/openapi/v1.json...
powershell -NoProfile -Command "try { Invoke-WebRequest -Uri '%BASE_URL%/openapi/v1.json' -OutFile '%tmp%\openapi-spec-react.json' -ErrorAction Stop; Write-Host '[OK] OpenAPI specification fetched' } catch { Write-Host '[ERROR] Failed to download OpenAPI specification'; exit 1 }"

if errorlevel 1 (
    echo [ERROR] Failed to fetch OpenAPI specification
    exit /b 1
)

REM Verify the spec file
if not exist "%tmp%\openapi-spec-react.json" (
    echo [ERROR] OpenAPI spec file not created
    exit /b 1
)

REM Generate TypeScript client using NSwag
echo.
echo [INFO] Generating TypeScript client using NSwag...
echo [INFO] Configuration: %CONFIG_FILE%
echo.

call nswag run "%CONFIG_FILE%" /variables:BaseUrl="%BASE_URL%"

if errorlevel 1 (
    echo [ERROR] Client generation failed
    exit /b 1
)

echo [OK] Client generation completed successfully
echo.

REM Verify generated files
if exist "%OUTPUT_DIR%\src\api\generated.ts" (
    echo [OK] Generated client file: %OUTPUT_DIR%\src\api\generated.ts
    for %%A in ("%OUTPUT_DIR%\src\api\generated.ts") do (
        set /a "size=%%~zA / 1024"
        echo [INFO] File size: !size! KB
    )
) else (
    echo [ERROR] Generated client file not found
    exit /b 1
)

REM Create index file for easier imports
echo [INFO] Creating index file for exports...
(
    echo /**
    echo  * Auto-generated API Client from OpenAPI specification
    echo  * Generated by: generate-react-client.bat
    echo  * 
    echo  * DO NOT EDIT: This file is generated automatically.
    echo  * Any changes will be overwritten when regenerating.
    echo  */
    echo.
    echo export * from './generated';
) > "%OUTPUT_DIR%\src\api\index.ts"
echo [OK] Index file created

REM Format generated files with Prettier if available
where prettier >nul 2>nul
if errorlevel 0 (
    echo [INFO] Formatting generated code with Prettier...
    call prettier --write "%OUTPUT_DIR%\src\api\generated.ts" 2>nul
    if errorlevel 0 (
        echo [OK] Code formatted
    ) else (
        echo [WARNING] Prettier formatting failed (non-critical)
    )
) else (
    echo [WARNING] Prettier not installed. Skipping code formatting...
)

REM Generate documentation
echo [INFO] Generating client documentation...
(
    echo # Auto-Generated React API Client
    echo.
    echo Generated from OpenAPI specification at: %BASE_URL%/openapi/v1.json
    echo.
    echo ## Generated Files
    echo.
    echo - `src/api/generated.ts` - Main API client and types
    echo - `src/api/index.ts` - Export barrel for easier imports
    echo.
    echo ## Usage
    echo.
    echo ### Import the Client
    echo.
    echo ```typescript
    echo import { TodoApiClient } from '@/api/generated';
    echo.
    echo const apiClient = new TodoApiClient();
    echo ```
    echo.
    echo ### Make API Calls
    echo.
    echo ```typescript
    echo const todos = await apiClient.getTodos(1, 10^);
    echo ```
    echo.
    echo ## Regenerating the Client
    echo.
    echo To regenerate the client after API changes:
    echo.
    echo ```bash
    echo cd clients/generation
    echo .\generate-react-client.bat
    echo ```
    echo.
    echo ## Important Notes
    echo.
    echo - Warning DO NOT EDIT the generated files directly
    echo - Generated files are overwritten on every regeneration
    echo - All customizations should be done in wrapper/adapter classes
    echo - Extend the generated client classes if you need custom behavior
    echo.
) > "%OUTPUT_DIR%\README.md"
echo [OK] Documentation created

REM Summary
echo.
echo ============================================================================
echo  GENERATION COMPLETE
echo ============================================================================
echo [OK] React API client generated successfully!
echo.
echo [INFO] Next steps:
echo   1. Install/update dependencies in React project
echo   2. Import from: import { TodoApiClient } from '@/api/generated'
echo   3. Create API client instance and use in your code
echo.
echo [INFO] Generated files location: %OUTPUT_DIR%
echo.

endlocal
exit /b 0
